[package]
name = "systest"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
build = "build.rs"

[dependencies]
curl-sys = { path = "../curl-sys" }
libc = "0.2"

[build-dependencies]
ctest = "0.2"
cc = "1.0"
