FROM ubuntu:16.04

RUN apt-get update
RUN apt-get install -y --no-install-recommends \
  curl \
  ca-certificates \
  gcc \
  make \
  libc6-dev \
  libssl-dev \
  pkg-config

ADD ./install-cmake.sh /install-cmake.sh
RUN /install-cmake.sh
