FROM ubuntu:16.04

RUN apt-get update
RUN apt-get install -y --no-install-recommends \
  curl \
  ca-certificates \
  make \
  libc6-dev \
  gcc \
  gcc-mingw-w64-x86-64 \
  libz-mingw-w64-dev

ADD ./install-cmake.sh /install-cmake.sh
RUN /install-cmake.sh
